server:
  port: 8080

auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168

spring:
  datasource:
    url: jdbc:postgresql://db.ftotcypbwohhbpelfbsy.supabase.co:5432/postgres
    username: postgres
    password: UOXVygOx0jmV9gR2
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: dev

cloud:
  aws:
    credentials:
      accessKey: AKIA2S26HGZE2WS4RYDE
      secretKey: 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
